travis:
  secure:
    BINSTAR_TOKEN: mSTRKWP1u6oORmo9rLfinWGFIDmrGUo/d/+gwRHYBQcMaVTbQ3dEyKfwKYhCueOiWM8sZDvLlERmYq9x49XEViwaVXgjyGZRHDlmJBOKe8Sy29RwoM/Dn9mcPUsDyWHbaintaVjEGXlwuyUFFap97fTk8yVDM33W96hiNxCL2YP9/kjVPFkW72e2q4bT+DvO1rR7t9wxW9fj1dyHkCQqn+mB8UXod8kA0DYBTqFdFdtjuMqDZN51BG4t1plEf2TZ78WxaTnOHjSbrw/dnq+5+T7FpTi0OR5uz2UCAmUKNhOMGxRGtG7k7MEBdq6PA8DLQIEsGve5GlFwNoHHtxLczqZguM1SUr59mH9GZFRBNw/Ii2cMaa5P59T27TOXH2D4pwL7qiYHyp7k77smZy1qwKMMKZjBcc6EAPoNoUeLNmAl1HSZl9n2g7L/ldJM5HWGQp75JAnJVYXCROysMpuzUf6EIrVUqzlLAgItK8fMToZolzSpqlG65Afh7t0H2fToCzMJYvlrX8nQw+bv3xoNFMoXwKdZ2iVp1HfSwAFv5J1W2itvaoJGMhO2OyqXckkZ0Q3X2Vk1LPnFsZgpJCgjNJm1nsbm6PEfLMgC57VSx0PDJPpyjqOljx7mx/t6lGDXwGokScZGhFBJVziW1g6sv+9ii/nVFVBcXSJcZmKyrMs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
